### PR TITLE
add: solutions to A2OJ Ladder 11

### PR DESCRIPTION
**Pull request by thunderfreak**
Added a few solutions to your repo as per issue discussed in #1 
Would love for you to review and merge if everything looks great!

### CODE REVIEW

**Comment by animeshbhakat** [comment]
Thanks for Contributing!

**Comment by thunderfreak** [comment]
@animeshbhakat could you please tag my contribution with **hacktoberfest-accepted** label so that it gets counted towards my contributions this month? Thanks in advance :)
Alternatively you could also add the **hacktoberfest** topic to the repo to opt the project into Hacktoberfest

**Comment by animeshbhakat** [comment]
@thunderfreak hacktoberfest topic is already there in the topic section. please check hacktoberfest dashboard to see if this PR is counted for hacktoberfest or not. If there is any issue do let me know.

**Comment by thunderfreak** [comment]
@animeshbhakat Hey, just checked. The PR got counted for hacktoberfest. Thanks!

**Pull request merged**
